#!/bin/bash

set -xe

# Download the sources, if not already done.
spectool -g spark2014-test.spec

# Build the SRPM.
fedpkg --release f40 --name spark2014-test srpm

# Upload the SRPM and run the tests.
copr-cli build -r fedora-40-x86_64 "dvraaij/ada" \
         spark2014-test-0^20240111gitce5fad0-1.fc40.src.rpm
